# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#509475" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#FF5345", bold = true, italic = true, underline = true }
find_position = { fg = "#D2689C", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#549e6a", bg = "#549e6a" }
marker_cut      = { fg = "#459451", bg = "#FF5345" }
marker_marked   = { fg = "#509475", bg = "#ACD4CF" }
marker_selected = { fg = "#459451", bg = "#459451" }

# Count
count_copied   = { fg = "#111c18", bg = "#549e6a" }
count_cut      = { fg = "#111c18", bg = "#459451" }
count_selected = { fg = "#111c18", bg = "#509475" }

# Border
border_symbol = "│"
border_style  = { fg = "#53685B" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#23372B", bg = "#509475", bold = true }
inactive = { fg = "#509475", bg = "#23372B" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#23372B", bg = "#509475", bold = true }
normal_alt  = { fg = "#509475", bg = "#23372B" }

# Select mode
select_main = { fg = "#23372B", bg = "#549e6a", bold = true }
select_alt  = { fg = "#509475", bg = "#23372B" }

# Unset mode
unset_main = { fg = "#23372B", bg = "#D2689C", bold = true }
unset_alt  = { fg = "#509475", bg = "#23372B" }

# : }}}


# : Status bar {{{

[status]
overall = { fg = "#509475" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }


# Progress
progress_label = { fg = "#23372B", bold = true }
progress_normal = { fg = "#509475", bg = "#23372B" }
progress_error = { fg = "#FF5345", bg = "#23372B" }

# Permissions
perm_sep   = { fg = "#509475" }
perm_type  = { fg = "#549e6a" }
perm_read  = { fg = "#459451" }
perm_write = { fg = "#FF5345" }
perm_exec  = { fg = "#D2689C" }


# : }}}

# : Pick {{{

[pick]
border = { fg = "#509475" }
active = { fg = "#D2689C", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#509475" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#509475" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#509475" }
title   = {}
hovered = { fg = "#D2689C", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#53685B" }
cand            = { fg = "#549e6a" }
rest            = { fg = "#C1C497" }
desc            = { fg = "#D2689C" }
separator       = "  "
separator_style = { fg = "#626880" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#549e6a" }
run     = { fg = "#D2689C" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#111c18", bg = "#C1C497" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#549e6a" }
title_warn  = { fg = "#FF5345" }
title_error = { fg = "#459451" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#459451" },

	# Media
	{ mime = "video/*", fg = "#FF5345" },
	{ mime = "audio/*", fg = "#FF5345" },

	# Archives
	{ mime = "application/zip",             fg = "#D2689C" },
	{ mime = "application/x-tar",           fg = "#D2689C" },
	{ mime = "application/x-bzip*",         fg = "#D2689C" },
	{ mime = "application/x-bzip2",         fg = "#D2689C" },
	{ mime = "application/x-7z-compressed", fg = "#D2689C" },
	{ mime = "application/x-rar",           fg = "#D2689C" },
	{ mime = "application/x-xz",            fg = "#D2689C" },

	# Documents
	{ mime = "application/doc",        fg = "#549e6a" },
	{ mime = "application/epub+zip",   fg = "#549e6a" },
	{ mime = "application/pdf",        fg = "#549e6a" },
	{ mime = "application/rtf",        fg = "#549e6a" },
	{ mime = "application/vnd.*",      fg = "#549e6a" },

	# Fallback
	{ name = "*", fg = "#2DD5B7" },
	{ name = "*/", fg = "#509475" }
]

# : }}}
